- name: Install and Configure Telegraf
  when: teloshost_telegraf and ansible_facts['distribution_major_version'] != "14" and not ("telegraf" in ansible_local and "general" in ansible_local['telegraf'] and "skip_install" in ansible_local['telegraf']['general'] and ansible_local['telegraf']['general']['skip_install'] == "true")
  include_role:
    name: dj-wasabi.telegraf
